account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('registration/', registration_view, name='registration'),
    path('logout/', logout_view, name='logout')
]

messApp/urls.py
from django.urls import path
from . import views

app_name = 'messApp'

urlpatterns = [
    path('', views.index, name="index"),
    # path('member/', views.MemberView.as_view(), name='member'),
    # path('member/<pk>', views.MemberDetails.as_view(), name="member_details"),
    path('dashbroad/<username>', views.member_dashbroad, name="dash_broad"),
    path('expense/', views.ExpenseView.as_view(), name="expense"),
    path('deposit/', views.balance_view, name="balance"),
    path('breakfast/', views.breakfastview, name="breakfast"),
    path('launch/', views.launchview, name="launch"),
    path('dinner/', views.dinnerview, name="dinner"),
    path('meal/', views.mealview, name="meal"),
]

mess_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messApp.urls', namespace='messapp')),
    path('', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    {% block css %}
    {% endblock%}

  </head>
  <body>
    {% url "messapp:index" as index_url %}
    {% url "messapp:dash_broad" username=request.user as dashbroad_url %}
    {% url "messapp:expense" as expense_url %}
    {% url "messapp:breakfast" as breakfast_url %}
    {% url "messapp:launch" as launch_url %}
    {% url "messapp:dinner" as dinner_url %}
    {% url "messapp:meal" as meal_url %}
    {% url "messapp:balance" as balance_url %}
  <!--<header>-->
    <!--<div class="container">-->
      <!--<div class="row">-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{{ index_url }}">Bazar Management System</a>
          <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item {% if request.path == index_url %}active{% endif%}">
                <a class="nav-link" href="{{ index_url }}">Home <span class="sr-only">(current)</span></a>
              </li>
                <li class="nav-item {% if request.path == expense_url %}active{% endif%}">
                <a class="nav-link" href="{{ expense_url }}">Expense</a>
              </li>
              <li class="nav-item {% if request.path == meal_url %}active{% endif%}">
                <a class="nav-link" href="{{ meal_url }}">Meal</a>
              </li>
              <li class="nav-item {% if request.path == breakfast_url %}active{% endif%}">
                <a class="nav-link" href="{{ breakfast_url }}">Breakfast</a>
              </li>
              <li class="nav-item {% if request.path == launch_url %}active{% endif%}">
                <a class="nav-link" href="{{ launch_url }}">Launch</a>
              </li>
              <li class="nav-item {% if request.path == dinner_url %}active{% endif%}">
                <a class="nav-link" href="{{ dinner_url }}">Dinner</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                </li>
                <li class="nav-item ml-4 {% if request.path == dashbroad_url %}active{% endif%}">
                  <a class="nav-link py-2 px-4 bg-success text-white rounded" href="{{ dashbroad_url }}">{{ request.user|title }}</a>
                </li>
               {% else %}
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'account:registration' %}">Registration</a>
                </li>
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'account:login' %}">login</a>
                </li>
              {% endif %}
            </ul>
          </div>
      </nav>
      <!--</div>-->
    <!--</div>-->
  <!--</header>-->

    {% block content %}
    {% endblock %}
    <footer class="bg-dark pt-3 pb-3">
      <div class="container">
        <div class="row">
              <p class="text-light mb-0 mx-auto">Copyright © 2018 | Bazar Management System | Developed By <span class="bg-white text-dark p-2">Noman</span></p>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock%}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}{% endblock %}

    {% block css %}
    {% endblock %}

    {% block content %}
    <section class="d-flex align-items-center justify-content-center" style="height:80vh">

                 <div class="text-center" style="height:auto">
                     <h1>Welcome To Bazar Management System.</h1>
                    {% if request.user.is_authenticated %}
                        <h3 class="mt-5">Hello <mark>{{ request.user.username|title }}</mark></h3>
                    {% else %}
                        <a href="{% url 'account:login' %}" class="btn btn-success">Login</a>
                        or
                        <a href="{% url 'account:registration' %}" class="btn btn-success">Registration</a>

                    {% endif %}
                </div>

    </section>
    {% endblock %}

    {% block js %}
    {% endblock %}